# Generated by Django 3.0.2 on 2020-01-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200107_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='type',
            new_name='type_publication',
        ),
    ]
