# Generated by Django 3.0.2 on 2020-01-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200108_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dewey',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='dewey',
            name='bg_color',
            field=models.CharField(default='*', max_length=7),
        ),
        migrations.AddField(
            model_name='dewey',
            name='text_color',
            field=models.CharField(default='*', max_length=7),
        ),
    ]
